repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-yaml
        exclude: ^chart/
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.23
  hooks:
  - id: helmlint
    exclude: ^chart\/templates\/NOTES\.txt$
